[package]
name = "event-source"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
x11rb = { path = "../../x11rb/x11rb", default-features = false, features = ["cursor", "render"]}
