[profile.release]
overflow-checks = true # I prefer panics over wraps

[profile.lto]
codegen-units = 1 # Better optimization
debug = false # Inherits from release so should actually do nothing but whatever
inherits = "release"
lto = true # link time optimization
strip = true # smaller binary
