[profile.dev]
panic = "abort" # No std requirement

[profile.release]
panic = "abort" # No std requirement

[profile.lto]
panic = "abort" # No std requirement
codegen-units = 1 # Better optimization
debug = false # Inherits from release so should actually do nothing but whatever
inherits = "release"
lto = true # link time optimization
strip = true # smaller binary