[package]
name = "pgwm"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
config-file = ["pgwm-core/config-file"]
default = ["xinerama", "status-bar", "config-file"]
debug = ["pgwm-core/debug"]
xinerama = ["x11rb/xinerama"]
status-bar = ["pgwm-core/status-bar", "time"]

[dependencies]
heapless = "0.7.10"
fontdue = { git = "https://github.com/MarcusGrass/fontdue", branch = "rasterize-oneshot", default-features = false, features = ["simd"] }
pgwm-core = { path = "../pgwm-core" }
x11-keysyms = { git = "https://github.com/MarcusGrass/x11-keysyms", rev = "4b0f0e3516100666d18df4b6e8eb520b318e1dc9", features = ["miscellany", "latin1"] }
nix = { version = "0.22.3" }
thiserror = "1.0.31"
time = { version = "0.3.9", optional = true, default-features = false, features = ["formatting", "local-offset"] }
x11rb = { version = "0.9.0", default-features = false, features = ["cursor", "render"]}
