[package]
name = "event-collection"
version = "0.0.0"
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smol = "1.2.5"
event-lib = { path = "../event-lib" }

[dependencies.x11rb]
path = "../../../x11rb/x11rb"
features = ["all-extensions"]

[dependencies.futures-util]
version = "0.3"
default-features = false
features = ["async-await", "async-await-macro", "io", "std"]

[dependencies.futures-io]
version = "0.3"
default-features = false
