name: "CI"

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  full-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: "clippy,rustfmt"
      - uses: taiki-e/install-action@v2
        with:
          tool: "cargo-hack,cargo-deny"
      - name: Run wm-check
        shell: bash
        run: ./.local/wm_check.sh

