name: "CI"

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container: marcusgrass/pgwm-check:latest
    steps:
      - uses: actions/checkout@v3
      - name: Run check script
        run: cargo test

